name: ci cd client - prod
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test app
        run: |
          npm run build
      - name: Create backup directory and transfer files to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 63.32.5.152
          username: ubuntu
          key: ${{ secrets.PEM_FILE }}
          script: |
            TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
            mkdir -p ~/releases/$TIMESTAMP &&
            scp -r -i ${{ secrets.PEM_FILE }} dist/ ubuntu@63.32.5.152:~/test/$TIMESTAMP
