name: ci cd client - prod
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test app
        run: |
          npm run build

      - name: Create backup directory and transfer files to EC2 instance
        run: |
          echo "$KEY_CONTENTS" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@63.32.5.152 "mkdir -p ~/test/$TIMESTAMP && cat | tar xzf -" < dist.tar.gz
        env:
          KEY_CONTENTS: ${{ secrets.PEM_FILE }}
