name: ci cd client - prod
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test app
        run: |
          npm run build
      - name: Transfer files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: 63.32.5.152
          username: ubuntu
          key: ${{ secrets.PEM_FILE }}
          source: "dist/"
          target: "~/test/$(date +%Y-%m-%d_%H-%M-%S)"
          script: |
            mkdir -p ~/test/$(date +%Y-%m-%d_%H-%M-%S)
