name: ci cd client - prod
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test app
        run: |
          npm run build
          
      - name: Transfer files to EC2 instance
        env:
          HOST: 63.32.5.152
          USERNAME: ubuntu
          KEY: ${{ secrets.PEM_FILE }}
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          mkdir -p ~/test/$TIMESTAMP
          echo "$KEY" > key.pem
          scp -r -i key.pem dist/ $USERNAME@$HOST:~/test/$TIMESTAMP
          rm key.pem
