name: ci cd client - prod
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test app
        run: |
          npm run build
          
      - name: Transfer files to EC2 instance
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          mkdir -p ~/test/$TIMESTAMP
          scp -r -i ${{ secrets.PEM_FILE }} dist/ ubuntu@63.32.5.152:~/test/$TIMESTAMP
        env:
          PEM_FILE: ${{ secrets.PEM_FILE }}
