name: ci cd client - prod
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test app
        run: |
          npm run build

      - name: Create backup directory and transfer files to EC2 instance
        env:
          KEY_CONTENTS: ${{ secrets.PEM_FILE }}
        run: |
          echo "$KEY_CONTENTS" > key.pem
          chmod 400 key.pem
          eval $(ssh-agent -s)
          ssh-add key.pem
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          ssh ubuntu@63.32.5.152 "mkdir -p ~/test/$TIMESTAMP && cat > ~/test/$TIMESTAMP/key.pem && chmod 400 ~/test/$TIMESTAMP/key.pem" < key.pem
          scp -r -i key.pem dist/ ubuntu@63.32.5.152:~/test/$TIMESTAMP
